---
# Setup a PostgreSQL database for Galaxy CloudMan

- name: Initialize Galaxy database
  shell: "{{ postgresql_bin_dir }}/initdb -D {{ galaxy_db_dir }} creates={{ galaxy_db_dir }}/postgresql.conf"

- name: Set Postgres port number
  lineinfile: dest={{ galaxy_db_dir }}/postgresql.conf regexp='^#port\ =\ 5432' line='port = {{ galaxy_db_port }}'

- name: Check if PostgreSQL server is running
  stat: path={{ galaxy_db_dir }}/postmaster.pid
  register: postgres_running

- name: Restart Postgres
  shell: "{{ postgresql_bin_dir }}/pg_ctl -D {{ galaxy_db_dir }} -w -l {{ galaxy_db_log }} restart"
  when: postgres_running.stat.exists

- name: Start Postgres
  shell: "{{ postgresql_bin_dir }}/pg_ctl -D {{ galaxy_db_dir }} -w -l {{ galaxy_db_log }} start"
  when: not postgres_running.stat.exists

- name: Create galaxy role
  postgresql_user: port={{ galaxy_db_port }} name={{ galaxy_user_name }} role_attr_flags=CREATEDB,LOGIN

- name: Create galaxyftp role
  postgresql_user: port={{ galaxy_db_port }} name=galaxyftp role_attr_flags=LOGIN password={{ psql_galaxyftp_password }}

- name: Create galaxy database
  postgresql_db: port={{ galaxy_db_port }} name=galaxy owner={{ galaxy_user_name }}

